let images = [
    { url: "/images/nature-costanera-butterfly.png", id: 0, size: 3364, name: "", section: "portafolio"},
    { url: "/images/ba-recoleta.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-fac.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-cayena.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-yellow-flower3.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-sky.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-purple-flower.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-mush.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-si-orange-flower.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-flores.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-memory-fadu.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-purple.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-ship-inside.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-si-purple-white.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-day-moon.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-pink-sunset.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-little-bridge.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-cheiru.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-red-flowers.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-dragonfly.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-leaves.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-hidden-house.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-memory.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-ship-window.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-costanera-flower.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/menu-about.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/home-red-flower.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-costanera-fruit.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/menu-contact.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/menu-portfolio.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-musgo.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-delta-pink-flower.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/nature-yellow-flower2.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-si-bird.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/ba-day-moon2.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/head-portfolio.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-tree.png", id: 0, size: 3364, name: "", section: "portafolio" },
    { url: "/images/delta-tiny-flowers.png", id: 0, size: 3364, name: "", section: "portafolio" },
]

export { images };